---
# Source: micro-app/templates/deploy.yaml
# templates/deploy.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: micro-app-deployment  # Chart.yaml의 name을 가져옴
  labels:
    # appEnv 문법을 대문자로 바꾸고 쌍따옴표로 안전하게 감싸기
    environment: "DEVELOPMENT"
spec:
  # values.yaml의 replicaCount 주입
  replicas: 3
  selector:
    matchLabels:
      app: micro-app
  template:
    metadata:
      labels:
        app: micro-app
    spec:
      containers:
      - name: web-container
        # tag 값이 비어있다면(.Values.image.tag가 빈 문자열이면) "latest"를 기본값으로 사용!
        image: "nginx:latest"
        ports:
        - containerPort: 80
         # [교정] values.yaml에 구성한 resources 오브젝트를 인덴트 10칸 기준으로 동적 렌더링합니다.
        resources:
          limits:
            cpu: 200m
            memory: 128Mi
          requests:
            cpu: 50m
            memory: 64Mi
